#!/usr/bin/env node
// Aggregate parity/verdicts/*.json → updates parity-tracking.md Diff column,
// writes parity/sonnet-report.md (bucketed summary + per-page deltas).
//
// Usage:
//   node scripts/parity-report.mjs
//   node scripts/parity-report.mjs --no-tracker-update   # report only

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '..')
const VERDICTS_DIR = join(repo, 'parity', 'verdicts')
const SNAPSHOTS_DIR = join(repo, 'parity', 'snapshots')
const RUN_JSON = join(repo, 'parity', 'last-run.json')
const TRACKER_PATH = join(repo, 'parity-tracking.md')
const REPORT_PATH = join(repo, 'parity', 'sonnet-report.md')
const HTML_PATH = join(repo, 'parity', 'sonnet-report.html')

const VERDICT_TO_DIFF = {
  match: '✅ matches',
  minor: '🟡 minor diff',
  major: '❌ major diff',
  broken: '❌ broken',
}

function loadVerdicts() {
  if (!existsSync(VERDICTS_DIR)) {
    console.error(`no verdicts dir at ${VERDICTS_DIR}`)
    process.exit(1)
  }
  const files = readdirSync(VERDICTS_DIR).filter((f) => f.endsWith('.json'))
  return files.map((f) => JSON.parse(readFileSync(join(VERDICTS_DIR, f), 'utf-8')))
}

function updateTracker(verdicts) {
  if (!existsSync(TRACKER_PATH)) {
    console.warn(`tracker not found at ${TRACKER_PATH} — skipping update`)
    return
  }
  const byPath = new Map(verdicts.map((v) => [v.path, v]))
  const text = readFileSync(TRACKER_PATH, 'utf-8')
  const lines = text.split('\n').map((line) => {
    const m = /^\| `([^`]+)` \| ([^|]+) \| `([^`]+)` \| ([^|]+) \| ([^|]+) \| ([^|]+) \|(.*)$/.exec(line)
    if (!m) return line
    const path = m[1].trim()
    const v = byPath.get(path)
    if (!v) return line
    const newDiff = VERDICT_TO_DIFF[v.verdict] || m[5].trim()
    const note = `Sonnet: ${v.summary}`.replace(/\|/g, '\\|').slice(0, 120)
    return `| \`${path}\` | ${m[2].trim()} | \`${m[3].trim()}\` | ${m[4].trim()} | ${newDiff} | ${m[6].trim()} | ${note} |${m[7]}`
  })
  writeFileSync(TRACKER_PATH, lines.join('\n'))
  console.log(`updated ${TRACKER_PATH}`)
}

function bucketOf(path) {
  if (path === '/') return '0-homepage'
  const seg = path.replace(/^\/|\/$/g, '').split('/')
  if (seg.length >= 2) {
    if (seg[0] === 'blog') return 'A1-blog'
    if (seg[0] === 'glossary') return 'A2-glossary'
    if (seg[0] === 'stories') return 'A3-stories'
    if (seg[0] === 'whitepapers') return 'A4-whitepapers'
    if (seg[0] === 'webinars') return 'A5-webinars'
  }
  return 'other'
}

function writeReport(verdicts) {
  const buckets = {}
  for (const v of verdicts) {
    const b = bucketOf(v.path)
    ;(buckets[b] ||= []).push(v)
  }
  const total = verdicts.length
  const byVerdict = verdicts.reduce((acc, v) => { acc[v.verdict] = (acc[v.verdict] || 0) + 1; return acc }, {})

  const lines = []
  lines.push('# Sonnet parity report')
  lines.push('')
  lines.push(`Generated by \`scripts/parity-report.mjs\`. ${total} pages reviewed.`)
  lines.push('')
  lines.push('## Verdict totals')
  lines.push('')
  for (const k of ['match', 'minor', 'major', 'broken']) {
    if (byVerdict[k]) lines.push(`- **${k}**: ${byVerdict[k]}`)
  }
  lines.push('')
  lines.push('## By bucket')
  lines.push('')
  lines.push('| Bucket | match | minor | major | broken | total |')
  lines.push('|---|---|---|---|---|---|')
  for (const [b, vs] of Object.entries(buckets).sort()) {
    const c = vs.reduce((acc, v) => { acc[v.verdict] = (acc[v.verdict] || 0) + 1; return acc }, {})
    lines.push(`| ${b} | ${c.match || 0} | ${c.minor || 0} | ${c.major || 0} | ${c.broken || 0} | ${vs.length} |`)
  }
  lines.push('')

  const failures = verdicts.filter((v) => v.verdict === 'major' || v.verdict === 'broken')
    .sort((a, b) => a.path.localeCompare(b.path))
  if (failures.length > 0) {
    lines.push(`## Fixes needed (${failures.length})`)
    lines.push('')
    for (const v of failures) {
      lines.push(`### \`${v.path}\` — ${v.verdict}${v.confidence ? ' ('+v.confidence+' confidence)' : ''}`)
      lines.push(`${v.summary}`)
      lines.push('')
      if (v.deltas && v.deltas.length > 0) {
        for (const d of v.deltas) {
          lines.push(`- [${d.viewport}] [${d.severity}] [${d.where}] ${d.description}`)
        }
        lines.push('')
      }
      if (v.notes) { lines.push(`> ${v.notes}`); lines.push('') }
    }
  }

  const minor = verdicts.filter((v) => v.verdict === 'minor').sort((a, b) => a.path.localeCompare(b.path))
  if (minor.length > 0) {
    lines.push(`## Minor cosmetic diffs (${minor.length})`)
    lines.push('')
    for (const v of minor) lines.push(`- \`${v.path}\` — ${v.summary}`)
    lines.push('')
  }

  writeFileSync(REPORT_PATH, lines.join('\n'))
  console.log(`wrote ${REPORT_PATH}`)
}

function snapshotPathFor(slug, side, viewport) {
  return relative(dirname(HTML_PATH), join(SNAPSHOTS_DIR, slug, `${side}-${viewport}.png`))
}

function slugFor(path) {
  return path.replace(/^\//, '').replace(/\/$/, '').replace(/\//g, '__') || 'home'
}

const VERDICT_PALETTE = {
  match: { bg: '#d4f5d4', label: '#1f5d1f' },
  minor: { bg: '#fff3c0', label: '#7a5a00' },
  major: { bg: '#ffd0d0', label: '#7a0000' },
  broken: { bg: '#404040', label: '#fff' },
}

function escapeHtml(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

function renderHtmlPage(v) {
  const slug = v.slug || slugFor(v.path)
  const palette = VERDICT_PALETTE[v.verdict] || { bg: '#eee', label: '#333' }
  const viewports = ['mobile', 'tablet', 'desktop']
  const viewportBlocks = viewports.map((vp) => {
    const orig = snapshotPathFor(slug, 'original', vp)
    const built = snapshotPathFor(slug, 'built', vp)
    return `
      <div class="vp">
        <h4>${vp}</h4>
        <div class="pair">
          <a href="${orig}" target="_blank"><div class="cap">ORIGINAL (WP)</div><img src="${orig}" loading="lazy"></a>
          <a href="${built}" target="_blank"><div class="cap">BUILT (Astro)</div><img src="${built}" loading="lazy"></a>
        </div>
      </div>`
  }).join('')
  const deltaBlock = (v.deltas && v.deltas.length > 0) ? `
    <details open><summary>Deltas (${v.deltas.length})</summary>
      <ul>${v.deltas.map((d) => `<li><b>[${escapeHtml(d.viewport)}]</b> [${escapeHtml(d.severity)}] <i>${escapeHtml(d.where)}</i> — ${escapeHtml(d.description)}</li>`).join('')}</ul>
    </details>` : ''
  const notesBlock = v.notes ? `<details><summary>Notes</summary><p>${escapeHtml(v.notes)}</p></details>` : ''
  return `
    <section id="${slug}" class="page">
      <header>
        <span class="badge" style="background:${palette.bg};color:${palette.label}">${v.verdict.toUpperCase()}</span>
        <span class="conf">${escapeHtml(v.confidence || '')}</span>
        <code>${escapeHtml(v.path)}</code>
      </header>
      <p class="summary">${escapeHtml(v.summary || '')}</p>
      ${deltaBlock}
      ${notesBlock}
      <div class="viewports">${viewportBlocks}</div>
    </section>`
}

function writeHtmlReport(verdicts) {
  const ORDER = { major: 0, broken: 1, minor: 2, match: 3 }
  const sorted = [...verdicts].sort((a, b) => {
    const oa = ORDER[a.verdict] ?? 9, ob = ORDER[b.verdict] ?? 9
    if (oa !== ob) return oa - ob
    return a.path.localeCompare(b.path)
  })
  const byVerdict = verdicts.reduce((acc, v) => { acc[v.verdict] = (acc[v.verdict] || 0) + 1; return acc }, {})
  const tocItems = sorted.map((v) => {
    const slug = v.slug || slugFor(v.path)
    return `<a href="#${slug}" class="toc-${v.verdict}">${v.verdict[0].toUpperCase()} ${escapeHtml(v.path)}</a>`
  }).join('')
  const pages = sorted.map(renderHtmlPage).join('\n')
  const html = `<!doctype html>
<meta charset="utf-8">
<title>Sonnet parity report — ${verdicts.length} pages</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: system-ui, sans-serif; margin: 0; display: grid; grid-template-columns: 280px 1fr; min-height: 100vh; }
  nav { background: #f5f5f5; padding: 12px; overflow-y: auto; height: 100vh; position: sticky; top: 0; font-size: 12px; }
  nav h1 { font-size: 14px; margin: 0 0 8px; }
  nav .totals { margin-bottom: 12px; }
  nav .totals span { display: inline-block; margin-right: 6px; padding: 1px 6px; border-radius: 3px; font-size: 11px; }
  nav a { display: block; padding: 2px 4px; text-decoration: none; color: #333; font-family: monospace; border-radius: 3px; }
  nav a:hover { background: #ddd; }
  nav a.toc-major { color: #7a0000; font-weight: 600; }
  nav a.toc-minor { color: #7a5a00; }
  nav a.toc-match { color: #1f5d1f; }
  nav a.toc-broken { color: #fff; background: #404040; }
  main { padding: 16px 24px; }
  section.page { border: 1px solid #ddd; border-radius: 6px; padding: 12px 16px; margin-bottom: 18px; }
  section.page header { display: flex; gap: 10px; align-items: center; }
  section.page header code { font-size: 14px; }
  .badge { padding: 2px 8px; border-radius: 3px; font-weight: 700; font-size: 12px; }
  .conf { font-size: 11px; color: #777; }
  .summary { font-size: 14px; color: #444; margin: 6px 0 8px; }
  details { font-size: 13px; margin: 4px 0; }
  details summary { cursor: pointer; }
  details ul { margin: 4px 0 6px 18px; padding: 0; }
  details li { margin: 2px 0; }
  .viewports { display: flex; gap: 16px; margin-top: 10px; flex-wrap: wrap; }
  .vp { flex: 1 1 30%; min-width: 280px; }
  .vp h4 { margin: 0 0 4px; font-size: 12px; color: #555; text-transform: uppercase; }
  .pair { display: flex; gap: 4px; }
  .pair > a { flex: 1; min-width: 0; }
  .pair .cap { font-size: 10px; color: #888; }
  .pair img { width: 100%; height: auto; border: 1px solid #ccc; display: block; }
</style>
<nav>
  <h1>Sonnet parity — ${verdicts.length} pages</h1>
  <div class="totals">
    ${Object.entries(byVerdict).map(([k, v]) => `<span style="background:${(VERDICT_PALETTE[k]||{}).bg};color:${(VERDICT_PALETTE[k]||{}).label}">${k}: ${v}</span>`).join('')}
  </div>
  ${tocItems}
</nav>
<main>
  ${pages}
</main>`
  writeFileSync(HTML_PATH, html)
  console.log(`wrote ${HTML_PATH}`)
}

function main() {
  const noTracker = process.argv.includes('--no-tracker-update')
  const verdicts = loadVerdicts()
  console.log(`loaded ${verdicts.length} verdicts`)
  if (!noTracker) updateTracker(verdicts)
  writeReport(verdicts)
  writeHtmlReport(verdicts)
}

main()
